apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - cluster-issuer.yml     # for CertManager (HTTPS)
  # App
  - app/deployment.yml
#  - app/service.yml        # for networking if you have more than one pod, resolves ip to name
  - app/ingress.yml
  # MongoDB
  - mongodb/configmap.yml
